# **Auriel M.V. Fournier**

PhD Candidate - University of Arkansas - Fayetteville  

Arkansas Cooperative Fish and Wildlife Research Unit  
419.307.6261  amvander@uark.edu

## **Education**

2016 expected \hspace{4mm} University of Arkansas - Fayetteville  PhD in **Biological Sciences - Ecology and Evolutionary Biology  **  

*Distinguished Doctoral Fellowship Recipient*

2011 \hspace{4mm} Michigan Technological University  Bachelor of Science in **Wildlife Ecology and Management**  
Minor - Remote Sensing  \hspace{4mm} *Magna Cum Laude*

## **Research Experience**

**Graduate Research Assistant** - Dr. David Krementz   
University of Arkansas - Arkansas Cooperative Fish and Wildlife Research Unit  
August 2012 - Present  

Effects of wetland management strategies on habitat use of fall migrating rails on intensively-managed wetland complexes in Missouri.Performing distance based nocturnal ATV surveys for rails in wetland impoundments across the state of Missouri. Managing a four person field crew, working closely with state and federal land managers. Capturing rails, taking blood and feather samples.

**Undergraduate Research Grant** - Dr. Joseph Bump  
Michigan Technological University - Ecosystem Science Center  
May 2011 - Present  

Assessing the breeding location of Virginia Rails migrating through NW Ohio  with stable isotopes - *Manuscript in progress*

**Summer Undergraduate Research Fellowship** - Dr. Joseph Bump 
Michigan Technological University  
August 2010 - Dec 2011  

Developing a morphometric model to predict the sex of Virginia Rails. *Published in The Wildlife Society Bulletin 2013, Poster presented 2013*

**Undergraduate Research Grant** - Dr. David Flaspohler  
Michigan Technological University - Ecosystem Science Center  
May 2010 - March 2011  

Eye Color Variation across the geographic range of Golden-winged Warblers *Poster presented 2011*

**Summer Undergraduate Research Fellowship** - Dr. David Flaspohler 
Michigan Technological University  
May - Aug 2009  

## Publications
**Fournier, A.M.V.,** Sheildcastle, M.C., Fries, A.C., Bump, J.K., (2013) Developing a morphometric model to predict the sex of Virginia Rails The Wildlife Society Bulletin, 37: 881-88 [pdf]

## Work Experience 

**Science Writing Tutor** University of Arkansas Quality Writing Center  
May - July 2012  
Tutoring undergraduate and graduate students on proper scientific writing. Editing thesis,
dissertations, lab reports and other writing.

**Environmental Education Internship** Kellogg Bird Sanctuary, Michigan State University  
May - July 2012  
Planned and led outdoor ed programs for all ages; Developed a social media plan

**Bird Bander** Michigan Technological University - Dr. David Flaspohler  
February - May 2012  
Banded endemic and endangered birds in isolated forest patches on the Big Island of Hawaii.
Operated double high mist-nets to capture birds and take blood and feather samples.

**Volunteer Field Technician** Isle Royale National Park Michigan Technological University - Dr. Joseph Bump  
May 2011  
Worked full-time constructing aquatic moose and beaver exclosures in small inland lakes at Isle Royale National Park to study the aect of herbivory on plant communities.

**Remote Sensing/GIS Technician** Michigan Technological University - Dr. Mike Falkowski  
February 2010 - December 2011  
Delineated cover type from color and B/W photos from past seventy years; Identied beaver dams and identified water bodies were created by the dams; Processed raw LiDAR data into maps for later interpretation

**Field Technician** Michigan Technological University - Dan Haskell  
July 2010  
Trapped small mammals; Performed nocturnal audio boat surveys for frogs; Frequently talked to public about project

**Field Crew Leader** Michigan Technological University - Dr. Amber Roth   
March - June 2010  
Led a crew of three to gather blood, feather and toenail samples of Blue-winged and Golden-winged Warblers across five study sites in Minnesota and Wisconsin; Developed the time line, budget and travel plans as to cover the largest area and gather the most samples; Established contact and coordinated site access on local, state, federal and military properties

## Posters
2013 **Fournier, A.M.V.,** Krementz, D.G., Mengel, D.C., Raedeke, A.H., Ecology of Fall Migrating Sora in Missouri. *The Wildlife Society National Conference* - WI [link]

2011 **Fournier, A.M.V.,** Sheildcastle, M.C., Fries, A.C., Bump, J.K., Developing a morphometric model to predict the sex of Virginia Rails. *The Wildlife Society National Conference* - HI 

2011 **Fournier, A.M.V.,** Roth, A.M., Flaspohler, D.J., Assessing mechanisms for variation in the eyes of Golden-winged Warblers *Ecosystem Science Center Poster Session* - MI 

2010 **Fournier, A.M.V.,** Flaspohler, D.J., Habitat Classification and Biological Inventory of Pioneer Scout Reservation *Undergraduate Research Expo* - MI 

## Presentations 
2014 **Fournier, A.M.V.,** Krementz, D.G. The Response of Fall Migrating Sora to Wetland Management *Arkansas State Chapter of the Wildlife Society Spring Meeting*

2014 **Fournier, A.M.V.,** Krementz, D.G. The Use of U.A.V.s to Assess Wetland Vegetation Interspersion *Arkansas State Chapter of The Wildlife Society Spring Meeting*

2013 **Fournier, A.M.V.,** Krementz, D.G., Mengel, D.C., Raedeke, A.H., Phenology, Habitat Use of Fall Migrating Rails in Missouri. *Missouri Department of Conservation Annual Meeting*  

2013 **Fournier, A.M.V.,** Krementz, D.G., Mengel, D.C., Raedeke, A.H., Phenology, Habitat Use of Fall Migrating Rails in Missouri *Arkansas Coop Fish & Wildlife Research Unit Annual Meeting*

2013 **Fournier, A.M.V.,** Krementz, D.G., Mengel, D.C., Raedeke, A.H., Phenology, Habitat Use and CoOccurrence of Fall Migrating Yellow Rails in Missouri *Yellow Rail Virtual Symposium,* USFWS 2013

## Grants
2014 **Arkansas Audubon Society Trust** $1200 
*Migratory Stopover Timing, Survival and Habitat Use of Fall Migrating Sora in Managed Wetlands*  
2011 **Summer Undergraduate Research Fellowship** $3000 
*Developing A Morphometric Model to Predict the Sex of Virginia Rails*  
2011 **Ecosystem Science Center Undergraduate Research Grant** $750 
*What are the breeding and wintering areas of Virgina Rails which migrate through NW Ohio*  
2010 **Ecosystem Science Center Undergraduate Research Grant** $750 
*Assessing the relationship between eye spotting and breeding location in Golden-winged Warblers*  
2009 **Summer Undergraduate Research Fellowship** $3000
*Habitat classification and Biological Inventory of Pioneer Scout Reservation*

## Profesional Licenses and Certifications
Sub-permit bird banding license holder (11 years experience)  
NSC Defensive Driving II National Safety Council  
Defensive Driving AAA Driver Improvement Program   
CPR/First Aid - American Red Cross  
ATV Rider Certification - ATV Safety Institute 

## Teaching Experience
2014 **Scientific Writing Tutor** - Quality Writing Center - University of Arkansas   
2011 **Teaching Assistant** - Michigan Tech - Field Techniques  
2011 **Teaching Assistant** - Michigan Tech - Creating Your Success    
2011 **Teaching Assistant** - Michigan Tech - Ornithology  
2010 **Teaching Assistant** - Michigan Tech - Field Techniques  
2010 **Teaching Assistant** - Michigan Tech - Creating Your Success    

## Honors 

2012 **Distinguished Doctoral Fellowship** - University of Arkansas  
2011 **Outstanding Senior in Wildlife Ecology and Management** - Michigan Tech   
2010 **Member of the Year** - The Wildlife Society Michigan Tech Student Chapter  
2009 **Woman of Promise** - School of Forest Resources and Envi. Sci. - Michigan Tech

## Service & Outreach
2014 **Peer Reviewer** Waterbirds   
2014 **Science Fair Judge** Regional/Local Science Fairs NW Arkansas  
2013 **Peer Reviewer** The Wildlife Society Bulletin   
2013 **Science Outreach Blog** [Natural Austerity] (naturalausterity.blogspot.com)  
2013 **Outdoor Education Volunteer** Hobbs State Park, Arkansas  
2010 **Research Blog** [Boots and Binoculars] (aurielfournier.blogspot.com)  
2013 **Volunteer** The Wildlife Society National Conference, Milwaukee, WI  
2011 **North American Breeding Bird Survey Volunteer** U.S. Geological Survey  
2013 **Presentation** Springdale Alternative High School, Springdale, AR  
2011 **Volunteer** The Wildlife Society National Conference, Big Island, HI   
2011 **Panel Member** Wind Power Meeting - Upper Peninsula Environmental Coalition  
2011 **Outdoor Educator** W. U.P. Center for Science, Math and Envi. Education  
2011 **Owl Survey Volunteer** Michigan Bird Conservation Initiative  
2010 **Presentation** Copper Country Audubon Society  
2010 **Career Panel Member** Ohio Young Birder's Club Conference  
2009 **Presentation** Kirtland Bird Club - Cleveland, OH  
2009 **Presentation** Copper Country Audubon Society  
2009 **Bird Bander** (Six years) Black Swamp Bird Observatory  
2008 **Presentation** Ohio Young Birder's Club Conference   
2008 **Presentation** Black Swamp Bird Observatory Lunch Lecture  
2007 **Presentation** Ohio Young Birder's Club Conference 


## Professional Development


2014 **Applied Hierarchical Modeling Workshop** Patuxent Wildlife Research Center/Royle & Kery   
2013 **'Adehabitat' R Package Workshop** The Wildlife Society National Con/James Sheppard  
2013 **Symposium Planning Committee** The Wildlife Society National Con, Milwaukee, WI  
2013 **Occupancy Modeling Short Course** Humboldt State U./Darryl MacKenzie  
2013 **The Wildlife Society National Conference** Milwaukee, WI  
2011 **The Wildlife Society National Conference** Waikialoa, HI   
2011 **Midwest Bird Conservation and Monitoring Conference** Rockford, IL  
2011 **Guest Lecture** Ornithology - Michigan Tech. Univ. - 'Migration and Navigation'  
2010 **Midwest Fish and Wildlife Conference** Minneapolis, MN  
2010 **The Wildlife Society National Conference** Snowbird, UT  
2010 **Wildlife Diversity Conference** Ohio Department of Natural Resources - Columbus, OH  
2009 **International Association of Great Lakes Researchers Conference** Toledo, OH   
2009 **Wildlife Diversity Conference** Ohio Department of Natural Resources - Columbus, OH  

## Computer & Field Skills A.M.V. Fournier C.V. Page 5

- Advanced: ArcGIS (9 and 10), R
- Intermediate: Fragstats, Fusion, ERDAS Imagine, Systat
- Beginner: Latex, Presence, Markdown
- Field Skills: Map and Compass, GPS, Visual/Song Identication of Eastern Bird Species, Forestry Measurements, Operating ATVs, Power and Hand Tools, Canoe/Kayak, Manual Transmission, 4WD Trucks, Driving Trailers, Frog and Toad Surveys, Nocturnal Work, Small Engine Repair

## Leadership

**The Wildlife Society University of Arkansas Student Chapter**  
Secretary 2014 - Present  
Treasurer 2012 - 2014  

**Biology Graduate Student Association** University of Arkansas  
Treasurer 2014 - Present  
Vice President 2013 - 2014  

**The Wildlife Society Michigan Tech Student Chapter**  
Activities Chair 2008 - 2011  

**The Honors Institute** Michigan Technological University   
Treasurer, Secretary, Committee Chair 2008 - 2011

**The Birdbums** Student Birding Organization   
Founding Member & President 2008 - 2011

**Xi Sigma Pi Honors Fraternity** Michigan Tech Student Chapter  
Symposium Chair 2010 - 2011

**Society of Wetland Scientists** Michigan Tech Student Chapter  
Public Outreach Team 2009 - 2011

## Memberships
- **The Wildlife Society** National, Section, State, Student Chapter, Student Development Working Group, Wetlands Working Group, Spatial Ecology and Telemetry Working Group   

- **American Ornithologists Union**
- **Association of Field Ornithologists**
- **The Waterbirds Society**
- **NW Arkansas Audubon Society**
- **Black Swamp Bird Observatory**

[Boots and Binoculars]: www.aurielmvfournier.com

[Natural Austerity]: www.naturalausterity.com

[link]: http://figshare.com/articles/The_Ecology_of_Fall_Migrating_Sora_in_Missouri/840571

[pdf]: http://s3.amazonaws.com/file-storage.INDIVIDUAL-ACTIVITIES-CooperativeResearchUnits.digitalmeasures.usgs.edu/amvander/intellcont/Fournier%20et%20al._2013_Wildlife%20Society%20Bulletin_A%20Morphometric%20Model%20to%20Predict%20the%20Sex%20of%20Virginia%20Rails%20%28Rallus%20limicola%29-1.pdf